### ISSUE TITLE
Authorization errors when visiting site in Chrome

### ISSUE THREAD

**Issue by ZeissS** [cloudant-labs/replication.io#5]
I get a bunch of htaccess popups when visiting the site.

**Comment by BigBlueHat** [comment]
@ZeissS odd...still seeing this?

**Comment by kxepal** [comment]
@BigBlueHat cannot reproduce with Chrome 41

**Comment by BigBlueHat** [comment]
Yeah. Think it was temporary. Phew! :wink:
